name: PR Description Validation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR Description
        run: |
          keyword="fixes" # 원하는 키워드를 여기에 설정
          if ! grep -i "$keyword" $GITHUB_EVENT_PATH; then
            echo "Error: PR description must contain the keyword '$keyword'"
            exit 1
          fi
